name: Update Latest Update

on:
  push:
    branches:
      - main  # Replace with your main branch name

jobs:
  update_file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Get latest commit message
        id: commit_message
        run: echo "::set-output name=message::$(git log -1 --pretty=%B)"

      - name: Create or update latest_update.md
        run: |
          echo "# Latest Update" > latest_update.md
          echo "#### Commit Message:" >> latest_update.md
          echo "\`${{ steps.commit_message.outputs.message }}\`" >> latest_update.md

      - name: Commit and push changes
        run: |
          git add latest_update.md
          git commit -m "Update latest_update.md with latest commit message"
          git push
